name: Build and Publish

on:
  push:
    branches: 
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x" # adjust this to your project's .NET version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }} --output ./dist

      - name: Push Package to GitHub Packages
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "latest"

      - name: Push Package to GitHub Packages
        run: nuget push ./dist/*.nupkg -Source "github"
